### ISSUE TITLE
ارور در بررسی اینکه یک قابلیت به هدف اصابت می کند یا خیر

### ISSUE THREAD

**Issue by geeksesi** [SharifAIChallenge/AIC19-Client-Python#22]
سلام
من سعی دارم بررسی کنم که آیا قابلیت هیروی سنتری به حریفی که توی دید یک هیروی دیگه هست اصابت می کنه یا خیر.
تاکید می کنم هیرو در محدوده سنتری نیست و در درد  هیروی دیگه ای هست.
در فایل 
model > line : 531 > def : get_impact_cells
به دلیل اینکه هیرو در محدوده دید خود سنتری نیست ارایه ای خالی برمی گردونه و این ارایه خالی باعث متوقف شدن برنامه در
model > line : 762 > def : self.get_cells_in_aoe()
می شود. 
ارور کاملی که دریافت می کنم :
 ```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/geeksesi/univers/Ai_sharif/patronus/Network.py", line 68, in run
    self.message_handler(self.receive())
  File "patronus/Controller.py", line 83, in handle_message
    [new_world.current_turn])).start()
  File "patronus/Controller.py", line 88, in launch_on_thread
    action(new_world)
  File "/home/geeksesi/univers/Ai_sharif/patronus/AI.py", line 76, in action
    self.sentry_action(world, hero)
  File "/home/geeksesi/univers/Ai_sharif/patronus/AI.py", line 100, in sentry_action
    target_cell=opp_hero.current_cell
  File "/home/geeksesi/univers/Ai_sharif/patronus/Model.py", line 762, in get_ability_targets
    affected_cells.update(self.get_cells_in_aoe(cell, ability_constant.area_of_effect))
  File "/home/geeksesi/univers/Ai_sharif/patronus/Model.py", line 733, in get_cells_in_aoe
    for row in range(cell.row - area_of_effect, cell.row + area_of_effect + 1):
AttributeError: 'NoneType' object has no attribute 'row'

```

این ارور در مواقع دیگه مشاهده نمیشه و کد به درستی کار می کنه.دلیل اینکه بعضی اوقات در یکی از کلاینت ها چنین چیزی مشاهده می کنم رو نمی دونم.
مقادیری که من به تابع ارسال می کنم رو بررسی کردم ولی هیچ اشتباهی ندیدم.
اگر لازم می دونید مقادیر رو در زمان بروز مشکل بفرستم براتون

**Comment by armagg** [comment]
هیرویی که بر روی آن این تابع رو کال کردید قبل از کال ردن مرده بوده برای همین مشکل پیش اومده 
باگ بر روی ریپو تصحیح شد تا دیگه اکسپشن نده .
