### ISSUE TITLE
"TypeError: can only concatenate str (not "HeroName") to str" after commit f4733cbf10782b6ecdd939de009792ea4996da90 (HEAD -> master, tag: v1.2, origin/master, origin/HEAD)

### ISSUE THREAD

**Issue by 1-1is0** [SharifAIChallenge/AIC19-Client-Python#26]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/amirftma/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/amirftma/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/amirftma/Python/AIC/ourAIchallenge2019/Network.py", line 68, in run
    self.message_handler(self.receive())
  File "ourAIchallenge2019/Controller.py", line 72, in handle_message
    threading.Thread(target=self.launch_on_thread(self.client.pick, new_world)).start()
  File "ourAIchallenge2019/Controller.py", line 84, in launch_on_thread
    action(new_world)
  File "/home/amirftma/Python/AIC/ourAIchallenge2019/AI.py", line 61, in pick
    pick_up.select_hero()
  File "/home/amirftma/Python/AIC/ourAIchallenge2019/pickup.py", line 15, in select_hero
    logging.info("enemy hero %s" % opp)
  File "/home/amirftma/Python/AIC/ourAIchallenge2019/Model.py", line 164, in __str__
    return 'id:' + str(self.id) + '    name:' + self.name
TypeError: can only concatenate str (not "HeroName") to str

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/amirftma/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/amirftma/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/amirftma/Python/AIC/ourAIchallenge2019/Network.py", line 68, in run
    self.message_handler(self.receive())
  File "ourAIchallenge2019/Controller.py", line 72, in handle_message
    threading.Thread(target=self.launch_on_thread(self.client.pick, new_world)).start()
  File "ourAIchallenge2019/Controller.py", line 84, in launch_on_thread
    action(new_world)
  File "/home/amirftma/Python/AIC/ourAIchallenge2019/AI.py", line 61, in pick
    pick_up.select_hero()
  File "/home/amirftma/Python/AIC/ourAIchallenge2019/pickup.py", line 15, in select_hero
    logging.info("enemy hero %s" % opp)
  File "/home/amirftma/Python/AIC/ourAIchallenge2019/Model.py", line 164, in __str__
    return 'id:' + str(self.id) + '    name:' + self.name
TypeError: can only concatenate str (not "HeroName") to str

```

**Comment by 1-1is0** [comment]
if I want to print hero name I get the following error
```
    print(hero.name + " has these abilites " + str(hero.ability_names))
TypeError: unsupported operand type(s) for +: 'HeroName' and 'str'
```

**Comment by armagg** [comment]
after that commit we use Enum type for HeroName 
use this format : 
`print(hero.name.value + " has these abilites " + str(hero.ability_names))`

**Comment by 1-1is0** [comment]
thanks for letting us know :+1: 
at least fix your own code!!!

```
  File "/home/amirftma/Python/AIC/ourAIchallenge2019/Model.py", line 164, in __str__
    return 'id:' + str(self.id) + '    name:' + self.name
```
