### ISSUE TITLE
Hero is not moving

### ISSUE THREAD

**Issue by k3rn3lpanicc** [SharifAIChallenge/AIC19-Client-Python#6]
من یه هیرو رو حرکت میدم ولی حرکت نمیکنه , خونه های کناریش هم دیوار نیست . توی هر جهتی هم تست میکنم کار نمیکنه , تازه جهت پایین اررور هم میده
روی هر سه نقشه تست کردم نشد

**Comment by armagg** [comment]
حرکت هیرو ها توسط تیم های تست ،تست شده است. 
احتمالا دارید شیوه اشتباهی رو برای حرکت به کار میبرید 
همین جا اگر میشه نمونه کد رو بذارید تا بررسی کنیم

**Comment by k3rn3lpanicc** [comment]
`def move(self, world):`
`print(world.my_heroes[0].current_cell)`
`world.move_hero(hero=world.my_heroes[0],direction=Model.Direction.UP)`
`print("Move` UP")

هر چهار تا جهت رو تست کردم , کار نمیکنه , (جهت هایی که دیوار نیست رو هم تست کردم) . روی جهت پایین اررور هم میده ولی تو جهت های دیگه اررور نمیده ولی مختصاتش عوض نمیشه
وقتی جهت پایین میزنم این اررور رو میده : 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\a\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\a\Desktop\sharif\clients\1\Network.py", line 68, in run
    self.message_handler(self.receive())
  File "C:/Users/a/Desktop/sharif/clients/1/Controller.py", line 77, in handle_message
    threading.Thread(target=self.launch_on_thread(self.client.move, new_world)).start()
  File "C:/Users/a/Desktop/sharif/clients/1/Controller.py", line 84, in launch_on_thread
    action(new_world)
  File "C:\Users\a\Desktop\sharif\clients\1\AI.py", line 68, in move
    world.move_hero(hero=hero=world.my_heroes[0],direction=Model.Direction.Down)
  File "C:\Users\a\AppData\Local\Programs\Python\Python36\lib\enum.py", line 324, in `__getattr__`
    raise AttributeError(name) from None
AttributeError: Down

**Comment by RuhollahSeka** [comment]
در استفاده از
enum
باید از حروف بزرگ استفاده کنید. برای مثال باید به صورت زیر بنویسید:
Model.Direction.DOWN

در صورتی که دستور کاملا درست بفرستید، اعمال خواهد شد

**Comment by k3rn3lpanicc** [comment]
من از حروف بزرگ استفاده کردم ولی اعمال نشد , برای Direction.DOWN هم اررور میده

**Comment by k3rn3lpanicc** [comment]
امکانش هست خودتون یه نمونه کدی از پایتون که درست کار میکنه رو بفرستید؟

**Comment by houshangi** [comment]
manam hamin moshkelo daram , chetur bartarafesh kardid ?
